all := libaxil-nd
SONAME-libaxil-nd := axil-nd

LDLIBS-libaxil-nd := -laxil -lcorm -lxylem -lislet -lqsys
# -laxil-tty is referenced by no symbol on this line, so an ELF linker drops it
# from NEEDED unless the pair pins it -- and it must stay, the engine calls into
# axil-tty. Apple ld has neither option and fails with "unknown options", but it
# records every command-line library unconditionally, so the pair is ELF-only.
# Keep -laxil-tty BETWEEN the two: --as-needed is already back on by then, which
# is the whole point.
#
# A `LDLIBS-libaxil-nd-Darwin` override would NOT work, unlike the LDFLAGS one
# above: include.mk:68 and portable.mk:76 emit the per-uname variables as extra
# terms APPENDED to the base one, so the flags would still reach ld and
# -laxil-tty would be duplicated. The base variable has to be conditional.
ifneq ($(uname),Darwin)
LDLIBS-libaxil-nd += -Wl,--no-as-needed -laxil-tty -Wl,--as-needed
else
LDLIBS-libaxil-nd += -laxil-tty
endif
LDFLAGS-libaxil-nd := -L../axil-tty/lib
LDFLAGS-libaxil-nd-Darwin := -undefined dynamic_lookup

# Installed runtime data. Only htdocs/ goes through `share`: the mk framework
# word-splits that variable (include.mk:115) and 330 art paths contain spaces
# (e.g. "art/biome/tropical rainforest/20.jpeg"), which corrupts the install
# rule. art/ and man/ are installed by install-data below instead.
# htdocs/ is generated by `npm run build` (see §1.4 of RELEASE.md) and MUST
# exist before this, or the packages ship a client that 404s.
share != find ./htdocs -type f
share-dir := axil-nd

# J4.8 step 4: engine TUs (12 + split world.c/io.c/mods.c; libnd.o excluded).
# Compiled via `make smoke` for the smoke gate; since SESSION-9m they also
# LINK into lib/libaxil-nd.so (nd_api.c's 52 XY_IMPLs forward to the eng_*
# engine symbols, nd_xy.c delegates io to io.c), so plain `make`/`./test`
# run the REAL multi-TU engine.
# -fcommon: uapi/type.h's SIC_DECL emitted tentative on_*_id in every TU; the
# game events are XY hooks now (see src/nd_events.c), so the common merge is
# only still needed for whatever globals the engine TUs share -- kept until
# MODS.md Phase 3 re-checks it.
ENGINE-obj-y := \
	src/entity.o src/item.o src/look.o src/map.o src/match.o \
	src/mcp.o src/noise.o src/object.o src/spacetime.o src/speech.o \
	src/view.o src/wiz.o src/world.o src/io.o src/mods.o

libaxil-nd-obj-y := ${ENGINE-obj-y}

# MUST come after libaxil-nd-obj-y is defined. include.mk builds the library
# rule as `$(libtarget): lib ${LIB:%=src/%.o} ${LIB-obj-y}` -- and prerequisite
# lists are expanded when the rule is READ, i.e. at this -include. Recipes are
# expanded when they RUN, which is why the engine objects used to reach the link
# line but not the prerequisite list: the library was declared out of date by
# src/libaxil-nd.o alone, so `make` relinked yesterday's engine .o files and
# never recompiled an edited engine TU. With src/mods.o deleted the link then
# failed outright rather than rebuilding it. Anything referenced in a
# prerequisite list has to be set above this line.
-include ./../mk/include.mk

man: man/.stamp
man/.stamp: man-src/*.10
	@mkdir -p man
	@install -m 644 man-src/*.10 man/
	@touch $@
.PHONY: man

# man/ is runtime data read CWD-relative (src/man.c opens "man/<topic>.10"),
# not a build artefact of the library, but a plain `make` must produce it so a
# fresh clone can run the suite without any external tree.
all: man

smoke: man ${ENGINE-obj-y}

CFLAGS-entity-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-item-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-look-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-map-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-match-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-mcp-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-noise-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-object-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-spacetime-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-speech-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-view-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-wiz-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-world-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-io-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-mods-o := -fPIC -D_GNU_SOURCE -fcommon

smoke: man ${ENGINE-obj-y}
	@echo "engine TU smoke: ok"
.PHONY: smoke

CFLAGS += -g \
	-I../axil-tty/include \
	-DAXIL_PREFIX='"$(PREFIX)"' \
	-DAXIL_HTDOCS='"$(PREFIX)/share/axil-nd/htdocs"'

# Phase 0 gate: lib/ is build output only; the loader-resolved system
# libcorm must provide the three primitives. Fails if a stale local copy
# shadows it or a symbol is missing. No port file may reference a new symbol
# before this passes.
check-lib:
	@test ! -e lib/libcorm.so || { echo "lib/libcorm.so must not exist: lib/ is build output" >&2; exit 1; }
	@lib=$$(LD_LIBRARY_PATH=./lib ldd lib/libaxil-nd.so | sed -n 's/.*=> \(\/[^ ]*libcorm\.so\).*/\1/p'); \
	test -n "$$lib" || { echo "libcorm unresolved" >&2; exit 1; }; \
	for s in corm_get_copy corm_del_value corm_next_copy; do \
		nm -D --defined-only "$$lib" | grep -q " T $$s$$" || { echo "missing $$s" >&2; exit 1; }; \
		echo "ok $$s"; \
	done
.PHONY: check-lib

# demo module (see mods/demo/demo.c build comment). --no-execute-only is
# ARM-only and rejected by GNU ld on x86_64, so it is omitted here.
demo: mods/demo/demo.so
mods/demo/demo.so: mods/demo/demo.c include/papi/nd-xy.h
	cd mods && cc -shared -fPIC -I../include -I/usr/include -o demo/demo.so demo/demo.c
.PHONY: demo

# MODS.md §0.4: build every module named in mods.load. Each line is either a
# bare name (built at mods/<n>/<n>.so) or a path (built where it is named), so
# the one-repo-per-module layout works without copying anything into this
# tree. `make mods` is the module gate; test.sh runs it before booting axil.
MODS_LOAD := mods.load
# Pull the module list out with a character-class match rather than a `#`
# strip: make removes everything from an unescaped `#` to end of line BEFORE
# `$$` is expanded, so `-e 's/$$#.*//'` still loses the closing quote and make
# dies with "Unterminated quoted string" at parse time -- taking every target
# with it. Matching `[A-Za-z0-9_./-][...]*` against line start drops comments,
# blank lines and indented lines for free, since none of them can start with a
# name character, and keeps both a bare name and a sibling path.
modnames != sed -n 's/^\([A-Za-z0-9_.\/-][A-Za-z0-9_.\/-]*\).*/\1/p' \
	${MODS_LOAD} 2>/dev/null
# $(sort) is load-bearing, not tidiness: a module listed twice makes the
# per-module rules below declare one target twice, and make refuses the whole
# makefile with "target '...' given more than once in the same rule". A
# duplicated entry is exactly what a re-run looks like if a previous run died
# before restoring mods.load.
modnames := $(sort ${modnames})

# A path entry (contains '/') is already a full stem, so the artifact to build
# is that stem plus the suffix; a bare name is the in-tree `mods/<n>/<n>.so`.
# $(if) takes (cond,then,else) and $(findstring) yields the needle or the empty
# string, so the '/' case is the THEN branch. Getting these two the wrong way
# round silently drops path entries from the list: `make mods` then reports
# "Nothing to be done" for a module whose .so does not exist, which is how the
# out-of-tree build looked like it worked while building nothing.
mods: $(foreach m,${modnames},$(if $(findstring /,${m}),${m}.$(SO),mods/${m}/${m}.so))

# in-tree module: a bare name, so mods/<n>/<n>.so
mods/%.so: mods/%/%.c include/papi/nd-xy.h
	cd mods/$* && $(CC) -shared -fPIC -I../../include -I/usr/include \
		-o $*.so $*.c

# out-of-tree module: a line with a '/', built through the same nd-mod.mk that
# ships installed, so a sibling checkout is compiled exactly as it would be
# from $(PREFIX). Only ND_INC is redirected -- the XY headers come from the
# installed prefix, the same as for an installed module.
#
# Split out of ${modnames} with $(if $(findstring ...)) rather than
# $(filter %/%,...): make's pattern matching is not a "contains" operator.
# Measured on GNU Make 4.4.1 with `x := a/b demo c/d/e`:
#   $(filter %,$(x))    -> a/b demo c/d/e     (ok)
#   $(filter a%,$(x))   -> a/b                 (ok)
#   $(filter a/%,$(x))  -> a/b                 (ok)
#   $(filter /%,$(x))   ->                     (leading % never matches)
#   $(filter %b%,$(x))  ->                     (two % never match)
# so `%/%,...` silently yields the EMPTY list -- no rule defined, and make then
# reports "No rule to make target '../axil-nd-<mod>/<mod>.so'". $(findstring)
# has no such quirk and is what the `mods:` line above already uses.
# The recipe derives everything from $@ rather than from the foreach variable.
# A `$(foreach m,...)` variable is only in scope while the TARGET LINE is being
# expanded; recipes are expanded lazily, when the rule actually runs, by which
# point `m` is gone and `$(m)` expands to the empty string. The symptom is
# precise and misleading: the target came out right (so the rule was found and
# selected) while the recipe ran `MOD= ... -C  .so` and died on an empty name:
#   make -f nd-mod.mk MOD= ND_INC=.../include -C  .so
# $@ is an automatic variable, always in scope in a recipe. The stem is
# $(basename $@) because mods.load names the stem, not the .so.
#
# The prerequisite is FORCE, not nd-mod.mk, and that is a bug fix rather than a
# style choice. Nothing in THIS tree knows an out-of-tree module's sources, so
# any prerequisite list here can only name nd-mod.mk -- which is older than
# every .so, so make considers the target permanently up to date and never
# runs the recipe. Measured: after editing axil-nd-other/main.c,
#   -rw-r--r-- 18:34:18 other.so      <- older than the source
#   -rw-r--r-- 18:35:14 main.c
# `make mods` printed nothing for it, the engine loaded the STALE .so, and
# nd-other's new WARN markers never appeared -- so the suite failed on
# "nd-other: on_add first call" with the source right there in the log's own
# repo. This is MODS.md §2.1's bug (the engine linking yesterday's objects)
# one level out, and it is the same class: a build that silently ships stale
# code, which for a modding test is indistinguishable from a broken hook.
#
# So the .so is not treated as up-to-date at all: FORCE always makes the
# recipe run, and the recipe delegates to the module's own nd-mod.mk, which has
# the real `%.o: %.c` tracking and so still recompiles only what changed. The
# cost is one sub-make invocation per module, not a full rebuild.
$(foreach m,$(filter $(foreach n,${modnames},$(if $(findstring /,${n}),${n},)),${modnames}),$(m).$(SO)): FORCE
	$(MAKE) -f $(CURDIR)/nd-mod.mk MOD=$(notdir $(basename $@)) \
		ND_INC=$(CURDIR)/include -C $(patsubst %/,%,$(dir $(basename $@))) \
		$(notdir $@)

# Never a real file; exists only to be always-out-of-date. Declared .PHONY
# because an accidental file named FORCE would otherwise defeat the point.
FORCE:
.PHONY: mods FORCE

# README.md:31 documents `make test`; mk/include.mk defines no such target, so
# it silently did nothing. test.sh is the real suite and is self-contained
# (it generates man/ from man-src/ itself), so it needs no separate deps.
test: all
	@./test.sh
.PHONY: test

# art/ and man/ alongside htdocs/, per §6.2 of RELEASE.md. These cannot use the
# framework's `share` variable: include.mk:115 word-splits it, and 330 art paths
# contain spaces, which corrupts both the target list and the install recipe.
# `find -exec install -D` keeps each path quoted end to end.
install-data: man
	@dst=$(abspath $(DESTDIR)$(PREFIX))/share/axil-nd; \
	for d in art man; do \
		( cd $$d && find . -type f ! -name '.stamp' -exec install -D -m 644 {} "$$dst/$$d/{}" \; ) || exit 1; \
	done
.PHONY: install-data

# MODS.md §0.4: the module-facing API has to be installed, or a sibling
# ~/axil-nd-<name> repo has nothing to compile against. mk's install rule only
# covers include/${FOLDER} (FOLDER=ttypt, include.mk:19-21,104-108), so papi/
# is installed here, under its own prefix: modules use
# `-I$(PREFIX)/include/axil-nd` and keep writing `#include "papi/nd-xy.h"`.
#
# nd-mod.mk goes alongside it in share/, which is where a module's Makefile
# includes it from -- the same reason the engine's own htdocs/art/man live
# there rather than in the framework's word-split `share` list.
ND_PAPI := nd-hd.h nd-xy-types.h nd-xy.h nd-hooks.h

install-papi:
	@dst=$(DESTDIR)$(PREFIX)/include/axil-nd/papi; \
	install -d "$$dst" || exit 1; \
	for h in $(ND_PAPI); do \
		install -m 644 include/papi/$$h "$$dst/$$h" || exit 1; \
	done; \
	install -D -m 644 nd-mod.mk $(DESTDIR)$(PREFIX)/share/axil-nd/nd-mod.mk
.PHONY: install-papi

install: install-data install-papi
