all := libaxil-nd
SONAME-libaxil-nd := axil-nd

LDLIBS-libaxil-nd := -laxil -lcorm -lxylem -lislet -lqsys -Wl,--no-as-needed -laxil-tty -Wl,--as-needed
LDFLAGS-libaxil-nd := -L../axil-tty/lib
LDFLAGS-libaxil-nd-Darwin := -undefined dynamic_lookup

# Installed runtime data. Only htdocs/ goes through `share`: the mk framework
# word-splits that variable (include.mk:115) and 330 art paths contain spaces
# (e.g. "art/biome/tropical rainforest/20.jpeg"), which corrupts the install
# rule. art/ and man/ are installed by install-data below instead.
# htdocs/ is generated by `npm run build` (see §1.4 of RELEASE.md) and MUST
# exist before this, or the packages ship a client that 404s.
share != find ./htdocs -type f
share-dir := axil-nd

-include ./../mk/include.mk

man: man/.stamp
man/.stamp: man-src/*.10
	@mkdir -p man
	@install -m 644 man-src/*.10 man/
	@touch $@
.PHONY: man

# man/ is runtime data read CWD-relative (src/man.c opens "man/<topic>.10"),
# not a build artefact of the library, but a plain `make` must produce it so a
# fresh clone can run the suite without any external tree.
all: man

smoke: man ${ENGINE-obj-y}

# J4.8 step 4: engine TUs (12 + split world.c/io.c/mods.c; libnd.o excluded).
# Compiled via `make smoke` for the smoke gate; since SESSION-9m they also
# LINK into lib/libaxil-nd.so (nd_api.c's 52 XY_IMPLs forward to the eng_*
# engine symbols, nd_xy.c delegates io to io.c), so plain `make`/`./test`
# run the REAL multi-TU engine.
# -fcommon: uapi/type.h SIC_DECL emits tentative on_*_id in every TU; common
# merge keeps the multi-TU link single-definition.
ENGINE-obj-y := \
	src/entity.o src/item.o src/look.o src/map.o src/match.o \
	src/mcp.o src/noise.o src/object.o src/spacetime.o src/speech.o \
	src/view.o src/wiz.o src/world.o src/io.o src/mods.o

libaxil-nd-obj-y := ${ENGINE-obj-y}

CFLAGS-entity-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-item-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-look-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-map-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-match-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-mcp-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-noise-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-object-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-spacetime-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-speech-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-view-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-wiz-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-world-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-io-o := -fPIC -D_GNU_SOURCE -fcommon
CFLAGS-mods-o := -fPIC -D_GNU_SOURCE -fcommon

smoke: man ${ENGINE-obj-y}
	@echo "engine TU smoke: ok"
.PHONY: smoke

CFLAGS += -g \
	-I../axil-tty/include \
	-DAXIL_PREFIX='"$(PREFIX)"' \
	-DAXIL_HTDOCS='"$(PREFIX)/share/axil-nd/htdocs"'

# Phase 0 gate: lib/ is build output only; the loader-resolved system
# libcorm must provide the three primitives. Fails if a stale local copy
# shadows it or a symbol is missing. No port file may reference a new symbol
# before this passes.
check-lib:
	@test ! -e lib/libcorm.so || { echo "lib/libcorm.so must not exist: lib/ is build output" >&2; exit 1; }
	@lib=$$(LD_LIBRARY_PATH=./lib ldd lib/libaxil-nd.so | sed -n 's/.*=> \(\/[^ ]*libcorm\.so\).*/\1/p'); \
	test -n "$$lib" || { echo "libcorm unresolved" >&2; exit 1; }; \
	for s in corm_get_copy corm_del_value corm_next_copy; do \
		nm -D --defined-only "$$lib" | grep -q " T $$s$$" || { echo "missing $$s" >&2; exit 1; }; \
		echo "ok $$s"; \
	done
.PHONY: check-lib

# demo module (see mods/demo/demo.c build comment). --no-execute-only is
# ARM-only and rejected by GNU ld on x86_64, so it is omitted here.
demo: mods/demo/demo.so
mods/demo/demo.so: mods/demo/demo.c include/papi/nd-xy.h
	cd mods && cc -shared -fPIC -I../include -I/usr/include -o demo/demo.so demo/demo.c
.PHONY: demo

# README.md:31 documents `make test`; mk/include.mk defines no such target, so
# it silently did nothing. test.sh is the real suite and is self-contained
# (it generates man/ from man-src/ itself), so it needs no separate deps.
test: all
	@./test.sh
.PHONY: test

# art/ and man/ alongside htdocs/, per §6.2 of RELEASE.md. These cannot use the
# framework's `share` variable: include.mk:115 word-splits it, and 330 art paths
# contain spaces, which corrupts both the target list and the install recipe.
# `find -exec install -D` keeps each path quoted end to end.
install-data: man
	@dst=$(abspath $(DESTDIR)$(PREFIX))/share/axil-nd; \
	for d in art man; do \
		( cd $$d && find . -type f ! -name '.stamp' -exec install -D -m 644 {} "$$dst/$$d/{}" \; ) || exit 1; \
	done
.PHONY: install-data

install: install-data
